#!/bin/bash

# Author: arandr
# Date Created: 2022-11-27
# Date Modified: 2022-11-27
#
# Description:
# Fixes my screen setup for the two monitors I have in my office.
# Code was created by using the arandr program
#
# Usage:
# Just call fixscreen_office


# Fixes the screen setup for all 3 monitors
xrandr --output eDP-1 --mode 1920x1080 --pos 2560x1440 --rotate normal --output HDMI-1 --primary --mode 2560x1440 --pos 2560x0 --rotate normal --output DP-1 --off --output DP-2 --mode 2560x1080 --pos 0x0 --rotate normal

# Fixes the background image to scale to each screen properly
feh --bg-scale Pictures/background.jpg

